version: '3.3'

services:
  appserver:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
      - smtp:smtp
      - elasticsearch:elasticsearch
    volumes:
      - .:/app
      - ~/.composer/cache:/.composer/cache

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: shopware

  selenium:
    image: selenium/standalone-chrome:3.8.1
    shm_size: 2g
    environment:
      DBUS_SESSION_BUS_ADDRESS: /dev/null

  elasticsearch:
    build: dev-ops/docker/containers/elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144

  smtp:
    image: mailhog/mailhog